# Generated by Django 5.0.2 on 2025-09-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_candidate_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Rating from 1-5', null=True),
        ),
    ]
