# Generated by Django 5.2.6 on 2025-09-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feedbacktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_embedding',
            field=models.JSONField(blank=True, help_text='Resume text embedding for semantic matching', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills_embedding',
            field=models.JSONField(blank=True, help_text='Skills text embedding for semantic matching', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_embedding',
            field=models.JSONField(blank=True, help_text='Text embedding for semantic matching', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
