# Generated by Django 5.0.2 on 2025-09-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_candidate_embedding_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='embedding_updated_at',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume_embedding',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skills_embedding',
        ),
        migrations.RemoveField(
            model_name='job',
            name='embedding_updated_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_embedding',
        ),
        migrations.AddField(
            model_name='candidate',
            name='achievements',
            field=models.JSONField(blank=True, default=list, help_text='Notable achievements and awards'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Programming/spoken languages'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='notice_period',
            field=models.CharField(blank=True, help_text='Notice period for current job', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Portfolio website URL'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_location',
            field=models.CharField(blank=True, help_text='Preferred work location', max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='projects',
            field=models.JSONField(blank=True, default=list, help_text='List of projects with details'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='summary',
            field=models.TextField(blank=True, help_text='Professional summary from resume'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='visa_status',
            field=models.CharField(blank=True, help_text='Work authorization status', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_experience',
            field=models.JSONField(blank=True, default=list, help_text='Detailed work experience history'),
        ),
    ]
