# Generated by Django 5.0.2 on 2025-09-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_candidate_embedding_updated_at_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Add comprehensive fields to api_candidate table
            ALTER TABLE api_candidate ADD COLUMN summary TEXT NOT NULL DEFAULT '';
            ALTER TABLE api_candidate ADD COLUMN projects TEXT NOT NULL DEFAULT '[]';
            ALTER TABLE api_candidate ADD COLUMN work_experience TEXT NOT NULL DEFAULT '[]';
            ALTER TABLE api_candidate ADD COLUMN languages TEXT NOT NULL DEFAULT '[]';
            ALTER TABLE api_candidate ADD COLUMN achievements TEXT NOT NULL DEFAULT '[]';
            ALTER TABLE api_candidate ADD COLUMN linkedin_url VARCHAR(200) NOT NULL DEFAULT '';
            ALTER TABLE api_candidate ADD COLUMN github_url VARCHAR(200) NOT NULL DEFAULT '';
            ALTER TABLE api_candidate ADD COLUMN portfolio_url VARCHAR(200) NOT NULL DEFAULT '';
            ALTER TABLE api_candidate ADD COLUMN visa_status VARCHAR(100) NOT NULL DEFAULT '';
            ALTER TABLE api_candidate ADD COLUMN preferred_location VARCHAR(200) NOT NULL DEFAULT '';
            ALTER TABLE api_candidate ADD COLUMN notice_period VARCHAR(100) NOT NULL DEFAULT '';
            """,
            reverse_sql="""
            -- Remove comprehensive fields from api_candidate table
            ALTER TABLE api_candidate DROP COLUMN summary;
            ALTER TABLE api_candidate DROP COLUMN projects;
            ALTER TABLE api_candidate DROP COLUMN work_experience;
            ALTER TABLE api_candidate DROP COLUMN languages;
            ALTER TABLE api_candidate DROP COLUMN achievements;
            ALTER TABLE api_candidate DROP COLUMN linkedin_url;
            ALTER TABLE api_candidate DROP COLUMN github_url;
            ALTER TABLE api_candidate DROP COLUMN portfolio_url;
            ALTER TABLE api_candidate DROP COLUMN visa_status;
            ALTER TABLE api_candidate DROP COLUMN preferred_location;
            ALTER TABLE api_candidate DROP COLUMN notice_period;
            """
        ),
    ]
