# Generated by Django 5.2.6 on 2025-09-18 09:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20250916_1751'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('job_types', models.JSONField(blank=True, default=list)),
                ('total_estimated_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('telephonic', 'Telephonic'), ('video', 'Video'), ('technical', 'Technical'), ('hr', 'HR'), ('panel', 'Panel'), ('assignment', 'Assignment'), ('onsite', 'Onsite'), ('cultural', 'Cultural')], default='video', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(default=30)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
                ('interviewers', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('passing_criteria', models.JSONField(blank=True, default=dict)),
                ('auto_advance', models.BooleanField(default=False)),
                ('email_template', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='api.interviewflow')),
            ],
            options={
                'ordering': ['flow', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='interviewflow',
            index=models.Index(fields=['is_default'], name='api_intervi_is_defa_209079_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewflow',
            index=models.Index(fields=['created_at'], name='api_intervi_created_badf9f_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewround',
            index=models.Index(fields=['flow', 'order'], name='api_intervi_flow_id_e7adc9_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewround',
            index=models.Index(fields=['type'], name='api_intervi_type_8f1aae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewround',
            unique_together={('flow', 'order')},
        ),
    ]
