# Generated by Django 5.2.6 on 2025-09-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_interviewflow_interviewround_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='interview_stages',
            field=models.JSONField(blank=True, default=list, help_text='Interview process configuration with stages'),
        ),
    ]
