# Generated by Django 5.2.6 on 2025-10-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_interview_stages_to_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='assessment_completed',
            field=models.BooleanField(default=False, help_text='Whether assessment is completed'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='assessment_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Assessment score percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='assessment_time_taken',
            field=models.IntegerField(blank=True, help_text='Time taken in seconds', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='assessment_url',
            field=models.URLField(blank=True, help_text='WebDesk assessment URL'),
        ),
    ]
