# Generated by Django 5.2.6 on 2025-10-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_candidate_assessment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='assessment_password',
            field=models.CharField(blank=True, help_text='Password for assessment login', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='assessment_username',
            field=models.CharField(blank=True, help_text='Unique username for assessment login', max_length=100),
        ),
    ]
