# Generated by Django 5.2.6 on 2025-10-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_candidate_assessment_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='assessment_tab_switches',
            field=models.IntegerField(default=0, help_text='Number of tab switches detected'),
        ),
    ]
