# Generated by Django 5.2.6 on 2025-10-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_candidate_assessment_tab_switches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='assessment_disqualified',
            field=models.BooleanField(default=False, help_text='Whether candidate was disqualified for cheating'),
        ),
    ]
