# Generated by Django 5.2.6 on 2025-10-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_candidate_assessment_disqualified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='assessment_recording',
            field=models.FileField(blank=True, help_text='Video/audio recording of assessment', null=True, upload_to='assessment_recordings/'),
        ),
    ]
