# Generated by Django 5.2.6 on 2025-10-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_candidate_assessment_recording_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='assessment_responses',
            field=models.JSONField(blank=True, default=dict, help_text='Full assessment question responses with answers'),
        ),
    ]
