# Generated by Django 5.2.6 on 2025-10-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_assessment_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='assessment_audio_url',
            field=models.URLField(blank=True, help_text='Audio recording URL from WebDesk assessment'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='assessment_screen_url',
            field=models.URLField(blank=True, help_text='Screen recording URL from WebDesk assessment'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='assessment_video_url',
            field=models.URLField(blank=True, help_text='Video recording URL from WebDesk assessment'),
        ),
    ]
