# Generated by Django 5.2.6 on 2025-10-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_recording_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='assessment_screen_recording',
            field=models.FileField(blank=True, help_text='Screen recording of assessment', null=True, upload_to='assessment_screens/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='assessment_video_recording',
            field=models.FileField(blank=True, help_text='Camera video recording of assessment', null=True, upload_to='assessment_videos/'),
        ),
    ]
