# Generated by Django 5.2.6 on 2025-10-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_candidate_assessment_screen_recording_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='retell_additional_notes',
            field=models.TextField(blank=True, help_text='Additional notes from call analysis'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_availability_preference',
            field=models.CharField(blank=True, help_text='Candidate availability preference', max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_call_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Full call analysis from Retell AI'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_call_duration_ms',
            field=models.IntegerField(blank=True, help_text='Call duration in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_call_id',
            field=models.CharField(blank=True, help_text='Retell AI call ID', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_call_outcome',
            field=models.CharField(blank=True, help_text='Call outcome: Interview Scheduled/Callback Requested/Not Interested/Voicemail', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_call_status',
            field=models.CharField(blank=True, help_text='Call status: registered, ongoing, ended, error', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_call_successful',
            field=models.BooleanField(default=False, help_text='Whether call was successful'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_call_summary',
            field=models.TextField(blank=True, help_text='AI-generated call summary'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_call_type',
            field=models.CharField(blank=True, help_text='Call type: phone_call or web_call', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_candidate_timezone',
            field=models.CharField(blank=True, help_text='Candidate timezone', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_end_timestamp',
            field=models.BigIntegerField(blank=True, help_text='Call end timestamp (ms)', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_in_voicemail',
            field=models.BooleanField(default=False, help_text='Whether call went to voicemail'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_interest_level',
            field=models.CharField(blank=True, help_text='Candidate interest: High/Medium/Low/Not Interested', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_interview_scheduled',
            field=models.BooleanField(default=False, help_text='Was interview time confirmed?'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_is_qualified',
            field=models.BooleanField(default=False, help_text='Does candidate meet basic qualifications?'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Custom metadata from call'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_public_log_url',
            field=models.URLField(blank=True, help_text='Public URL for call logs'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_questions_asked',
            field=models.JSONField(blank=True, default=list, help_text='Questions asked by candidate'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_recording_url',
            field=models.URLField(blank=True, help_text='Retell call recording URL'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason if candidate rejected'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_scheduled_date',
            field=models.CharField(blank=True, help_text='Interview date YYYY-MM-DD', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_scheduled_datetime_iso',
            field=models.CharField(blank=True, help_text='ISO 8601 datetime string', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_scheduled_time',
            field=models.CharField(blank=True, help_text='Interview time HH:MM AM/PM', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_scheduled_timezone',
            field=models.CharField(blank=True, help_text='Interview timezone', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_start_timestamp',
            field=models.BigIntegerField(blank=True, help_text='Call start timestamp (ms)', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_technical_skills',
            field=models.JSONField(blank=True, default=list, help_text='Technical skills mentioned in call'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_transcript',
            field=models.TextField(blank=True, help_text='Full call transcript from Retell'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_transcript_object',
            field=models.JSONField(blank=True, default=list, help_text='Detailed transcript with timestamps'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_unavailable_dates',
            field=models.TextField(blank=True, help_text='Dates candidate is NOT available'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_user_sentiment',
            field=models.CharField(blank=True, help_text='Candidate sentiment: Positive/Neutral/Negative', max_length=20),
        ),
    ]
