# Generated by Django 5.2.6 on 2025-10-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_retell_call_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum years of experience required', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum years of experience required', null=True),
        ),
    ]
