# Generated by Django 5.2.6 on 2025-10-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_experience_years_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_range',
            field=models.CharField(blank=True, help_text='Experience range (e.g., "3-5", "5-7")', max_length=50),
        ),
    ]
