# Generated by Django 5.2.6 on 2025-10-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_experience_range_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.CharField(blank=True, help_text='Custom job ID (e.g., JOB-2024-001)', max_length=100, null=True, unique=True),
        ),
    ]
