# Generated by Django 5.2.6 on 2025-10-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_job_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='webdesk_email_sent',
            field=models.BooleanField(default=False, help_text='Whether WebDesk assessment email has been sent'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='webdesk_email_sent_at',
            field=models.DateTimeField(null=True, blank=True, help_text='When WebDesk email was sent'),
        ),
    ]
