# Generated by Django 5.2.6 on 2025-10-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_job_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='retell_next_retry_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled time for next retry attempt', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_retry_count',
            field=models.IntegerField(default=0, help_text='Number of call retry attempts'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_analysis',
            field=models.TextField(blank=True, help_text='AI analysis of interview performance'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_completed_at',
            field=models.DateTimeField(blank=True, help_text='When interview completed', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_duration',
            field=models.IntegerField(blank=True, help_text='Interview duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_link',
            field=models.URLField(blank=True, help_text='Link to AI video interview'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_questions_asked',
            field=models.JSONField(blank=True, default=list, help_text='Questions asked by AI'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_recording_url',
            field=models.URLField(blank=True, help_text='URL to recorded video'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_responses',
            field=models.JSONField(blank=True, default=list, help_text='Candidate responses'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_score',
            field=models.IntegerField(blank=True, help_text='Overall interview score 0-100', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_started_at',
            field=models.DateTimeField(blank=True, help_text='When interview started', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_status',
            field=models.CharField(default='pending', help_text='Status: pending/in_progress/completed', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_transcript',
            field=models.JSONField(blank=True, default=list, help_text='Full conversation transcript with timestamps'),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='feedback_form_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='feedback_form_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='interview_type',
            field=models.CharField(blank=True, choices=[('AI Assisted', 'AI Assisted'), ('Human Only', 'Human Only'), ('Hybrid', 'Hybrid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='assessment_password',
            field=models.CharField(blank=True, help_text='Password for assessment login', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='assessment_username',
            field=models.CharField(blank=True, help_text='Unique username for assessment login', max_length=100),
        ),
    ]
