# Generated by Django 5.2.6 on 2025-10-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_webdesk_email_sent_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='video_interview_analysis',
            field=models.TextField(blank=True, help_text='AI analysis of interview performance'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_completed_at',
            field=models.DateTimeField(blank=True, help_text='When interview completed', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_duration',
            field=models.IntegerField(blank=True, help_text='Interview duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_link',
            field=models.URLField(blank=True, help_text='Link to AI video interview'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_questions_asked',
            field=models.JSONField(blank=True, default=list, help_text='Questions asked by AI'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_recording_url',
            field=models.URLField(blank=True, help_text='URL to recorded video'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_responses',
            field=models.JSONField(blank=True, default=list, help_text='Candidate responses'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_score',
            field=models.IntegerField(blank=True, help_text='Overall interview score 0-100', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_started_at',
            field=models.DateTimeField(blank=True, help_text='When interview started', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_status',
            field=models.CharField(default='pending', help_text='Status: pending/in_progress/completed', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_interview_transcript',
            field=models.JSONField(blank=True, default=list, help_text='Full conversation transcript with timestamps'),
        ),
    ]
