# Generated by Django 5.2.6 on 2025-10-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_retell_retry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='retell_last_call_attempt',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last call attempt', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='webdesk_email_sent',
            field=models.BooleanField(default=False, help_text='Whether WebDesk assessment email has been sent'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='webdesk_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when WebDesk email was sent', null=True),
        ),
    ]
