# Generated by Django 5.2.6 on 2025-10-21 14:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_webdesk_and_retell_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address for sending emails', max_length=254)),
                ('password', models.CharField(help_text='Email password or app password', max_length=255)),
                ('host', models.CharField(default='smtp.gmail.com', help_text='SMTP host', max_length=255)),
                ('port', models.IntegerField(default=587, help_text='SMTP port')),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption')),
                ('from_name', models.CharField(blank=True, help_text='Display name for sender', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this email configuration is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
