# Generated by Django 5.2.6 on 2025-10-21 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_video_interview_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_user', models.EmailField(blank=True, max_length=254)),
                ('email_password', models.CharField(blank=True, max_length=500)),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('email_port', models.IntegerField(default=587)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
        migrations.AddField(
            model_name='interviewround',
            name='feedback_form_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='feedback_form_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='interview_type',
            field=models.CharField(blank=True, choices=[('AI Assisted', 'AI Assisted'), ('Human Only', 'Human Only'), ('Hybrid', 'Hybrid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='assessment_password',
            field=models.CharField(blank=True, help_text='Password for assessment login', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='assessment_username',
            field=models.CharField(blank=True, help_text='Unique username for assessment login', max_length=100),
        ),
    ]
