# Generated by Django 5.0.2 on 2025-11-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_role_to_usercredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='retell_last_call_attempt',
            field=models.DateTimeField(blank=True, help_text='Last call attempt timestamp', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_next_retry_time',
            field=models.DateTimeField(blank=True, help_text='Next scheduled retry time', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='retell_retry_count',
            field=models.IntegerField(default=0, help_text='Number of call retry attempts'),
        ),
    ]
