# Generated by Django 5.0.2 on 2025-11-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_allow_custom_roles'),
        ('api', '0029_candidate_retell_last_call_attempt_and_more'),
    ]

    operations = [
    ]
